jobs:
  include:
    - stage: build
      services:
        - mysql
    - stage: deploy
      script: skip
      services:
        - docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
        - docker-compose build web
      if: branch = dev
      env:
        - TAG=latest
      install:
        - docker tag $CONTAINER_TOMCAT $IMAGE_TOMCAT:$VERSION
        - docker tag $IMAGE_TOMCAT:$VERSION $IMAGE_TOMCAT:$TAG
        - docker push $IMAGE_TOMCAT:$TAG
        - docker push $IMAGE_TOMCAT:$VERSION
      if: branch = master
      env: TAG=dev
      install:
        - docker tag $CONTAINER_TOMCAT $IMAGE_TOMCAT:$TAG
        - docker push $IMAGE_TOMCAT:$TAG
language: java
stages:
  - build
  - deploy