language: java
services:
  - mysql
  - docker
install:
- mvn install -P docker -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  stages:
    - name: deploy
    env: VERSION=3.1
    if: branch = master
    env: TAG=latest
    - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
    - docker-compose build web
    - docker tag owasp/securityshepherd_tomcat:3.1 ismisepaul/shepherd_tomcat:$VERSION
    - docker tag ismisepaul/shepherd_tomcat:$VERSION ismisepaul/shepherd_tomcat:$TAG
    - docker push ismisepaul/shepherd_tomcat:$TAG
    - docker push ismisepaul/shepherd_tomcat:$VERSION
    if: branch = dev
    env: TAG=dev
    - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
    - docker-compose build web
    - docker tag owasp/securityshepherd_tomcat:3.1 ismisepaul/shepherd_tomcat:$VERSION
    - docker tag ismisepaul/shepherd_tomcat:$VERSION ismisepaul/shepherd_tomcat:$TAG
    - docker push ismisepaul/shepherd_tomcat:$TAG
    - docker push ismisepaul/shepherd_tomcat:$VERSION
