jobs:
  include:
    - stage: build
      services:
        - mysql
    - stage: deploy
      script: skip
      services:
        - docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
        - docker-compose build web
      if: branch = dev
      env: TAG=dev
      script: bash docker/push_dev.sh
      if: branch = master
      env: TAG=latest
      script: bash docker/push_master.sh
language: java
stages:
  - build
  - deploy