language: java
services:
  - mysql
  - docker
after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker-compose build
  - docker tag secshep_tomcat ismisepaul/shepherd:latest
  - docker push ismisepaul/shepherd:v3.1
