jobs:
  include:
    - stage: build
      services:
        - mysql
    - stage: deploy
      script: skip
      before_install:
        - mvn install -P docker -DskipTests
        - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
        - docker-compose build web
      if: branch = master
      env:
        - VERSION=3.1
        - TAG=latest
      install:
        - docker tag secshep_tomcat ismisepaul/shepherd_tomcat:$VERSION
        - docker tag ismisepaul/shepherd_tomcat:$VERSION ismisepaul/shepherd_tomcat:$TAG
        - docker push ismisepaul/shepherd_tomcat:$TAG
        - docker push ismisepaul/shepherd_tomcat:$VERSION
      if: branch = dev
      env: TAG=dev
      install:
        - docker tag secshep_tomcat ismisepaul/shepherd_tomcat:$TAG
        - docker push ismisepaul/shepherd_tomcat:$TAG
      services:
        - docker
language: java
stages:
  - build
  - deploy