jobs:
  include:
    - stage: build
      language: java
      script:
        - mvn clean install -Pdocker -DskipTests -B
        - docker-compose build
      services: docker
    - stage: unit-test
      services: mysql
      language: java
      script: "mvn test -B"
    - stage: integration-test
      services: 
        - mysql
        - docker
      language: java
      script: "mvn verify -DskipUTs=true -DmongoDocker -B"
      before_install:
        - mvn -Pdocker validate
    - stage: deploy
      name: "Deploy to Dockerhub"
      language: generic
      provider: script
      skip_cleanup: true
      script: skip
      services: docker
      before_install:
        - mvn install -Pdocker -DskipTests
        - docker-compose build web
      script: bash docker/scripts/deploy-dockerhub.sh $TRAVIS_BRANCH
stages:
  - build
  - unit-test
  - integration-test
  - name: deploy
    if: branch IN (master, dev) AND type = push
