name: Java Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Maven with Docker Profile
        run: mvn clean install -Pdocker -DskipTests -B
      - name: Docker Compose Build
        run: docker-compose build
