name: Deploy to Dockerhub
on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ismisepaul/securityshepherd

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Dump the environment variables from the dotenv file so they can be used to build the tomcat server
      - name: Set environment variables
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env

      - name: Build Maven with Docker Profile
        run: mvn install -Pdocker -DskipTests

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TOMCAT_DOCKER_VERSION=${TOMCAT_DOCKER_VERSION}
            TLS_KEYSTORE_FILE=${TLS_KEYSTORE_FILE}
            TLS_KEYSTORE_PASS=${TLS_KEYSTORE_PASS}
            ALIAS=${ALIAS}
            HTTPS_PORT=${HTTPS_PORT}
