name: Lint Code Base

on:
  push:
    branches: [master, dev]
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          # Uses GITHUB_TOKEN to mark the status of each individual linter run in the Checks section of a pull request
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
