# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ gh-workflows ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: Whitesource Unified Agent Scan
      env:
        APIKEY: ${{secrets.APIKEY}}
      run: |
        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        echo UA downloaded successfully
        export WS_ENABLEIMPACTANALYSIS=true
        export WS_REQUIREKNOWNSHA1=false
        export WS_RESOLVEALLDEPENDENCIES=false
        export WS_MAVEN_RESOLVEDEPENDENCIES=true
        export WS_MAVEN_AGGREGATEMODULES=true
        java -jar wss-unified-agent.jar -appPath ./target/owaspSecurityShepherd.war -d ./ -apikey $APIKEY -project GitHub-Workflow -product WS-Examples

