name: Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: core
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start MYSQL Server
        run: sudo /etc/init.d/mysql start
      - name: Modify MySQL Connection Variables
        run: |
          GITHUB_MYSQL_HOST_ID=$(docker ps | awk 'NR==2{print $1}')
          GITHUB_MYSQL_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${GITHUB_MYSQL_HOST_ID})
          sed -i "s/TEST_MYSQL_HOST=127.0.0.1/TEST_MYSQL_HOST=${GITHUB_MYSQL_HOST}/g" ${GITHUB_WORKSPACE}/.env
          sed -i 's/TEST_MYSQL_PORT=3306/TEST_MYSQL_PORT=8888/g' ${GITHUB_WORKSPACE}/.env
      - name: Unit Tests
        run: mvn test -B -e -X
      - name: Intergration Tests
        run: mvn -Pdocker validate
