name: Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: core
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start MYSQL Server
        run: sudo /etc/init.d/mysql start
      - name: Create Connection File
        run: |
          sed -i 's/databaseConnectionURL=jdbc:mysql:\/\/127.0.0.1:3306\//databaseConnectionURL=jdbc:mysql:\/\/127.0.0.1:8888/g' target/test-classes/conf/database.properties
      - name: Unit Tests
        run: mvn test -B -e -X
      - name: Intergration Tests
        run: mvn -Pdocker validate
