name: Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: core
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Security Shepherd Project
        run: mvn clean install -DskipTests -B
      - name: Start MYSQL Server
        run: sudo /etc/init.d/mysql start
      - name: Modify MySQL Connection File
        run: |
          MYSQL_HOST_ID=$(docker ps | awk 'NR==2{print $1}')
          MYSQL_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${MYSQL_HOST_ID})
          sed -i 's/databaseConnectionURL=jdbc:mysql:\/\/127.0.0.1:3306\//databaseConnectionURL=jdbc:mysql:\/\/${MYSQL_HOST}:8888/g' ${GITHUB_WORKSPACE}/target/test-classes/conf/database.properties
      - name: Unit Tests
        run: mvn test -B -e -X
      - name: Intergration Tests
        run: mvn -Pdocker validate
